services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DOCKER_HOST=tcp://host.docker.internal:2375
    ports:
      - "5000:5000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3001:3000"
